name: Generate ECR and S3 Documentation

on:
  workflow_call:
    inputs:
      ecr_file:
        description: 'Path to the ECR documentation file'
        required: true
        type: string
      s3_file:
        description: 'Path to the S3 documentation file'
        required: true
        type: string

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate ECR Documentation
        run: |
          echo "Generating ECR documentation..."
          # Replace with your actual ECR documentation generation command
          echo "ECR documentation generated" > ${{ inputs.ecr_file }}

      - name: Generate S3 Documentation
        run: |
          echo "Generating S3 documentation..."
          # Replace with your actual S3 documentation generation command
          echo "S3 documentation generated" > ${{ inputs.s3_file }}

      - name: Commit ECR and S3 Docs
        run: |
          git config --local user.name "rakeshkgang"
          git config --local user.email "rakeshkgang8057@hmail.com"
          git add ${{ inputs.ecr_file }} ${{ inputs.s3_file }}
          git commit -m "Update ECR and S3 Docs"
          git push
